import 'package:flutter/material.dart';
import 'package:bmt_app/apps/client/core/theme/client_colors.dart';
import 'package:bmt_app/apps/client/core/theme/client_typography.dart';

/// Edge length of the brand tile, in logical pixels.
///
/// The native launch frame bakes the same 96dp tile, so this value and the
/// `TILE_DP` constant in `tool/generate_splash_assets.py` move together.
const double kSplashBrandMarkSize = 96;

/// The rounded, elevated brand tile shown at the center of the splash.
///
/// Geometry is shared with the native launch frame (`assets/branding/
/// splash_mark.png`, generated by `tool/generate_splash_assets.py`): same
/// [kSplashBrandMarkSize], same 0.31 corner ratio, same glyph, dead center of
/// the screen — so the OS splash dissolves into this one without the mark
/// moving or resizing.
class SplashBrandMark extends StatelessWidget {
  const SplashBrandMark({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: kSplashBrandMarkSize,
      height: kSplashBrandMarkSize,
      decoration: BoxDecoration(
        gradient: ClientColors.primaryGradientFor(context),
        borderRadius: BorderRadius.circular(kSplashBrandMarkSize * 0.31),
        boxShadow: [
          BoxShadow(
            color: ClientColors.primary.withAlpha(90),
            blurRadius: 32,
            offset: const Offset(0, 14),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(kSplashBrandMarkSize * 0.19),
        child: Image.asset(
          'assets/branding/brand_glyph.png',
          fit: BoxFit.contain,
          errorBuilder: (_, _, _) => const Icon(
            Icons.route_rounded,
            color: ClientColors.textInverse,
            size: kSplashBrandMarkSize * 0.5,
          ),
        ),
      ),
    );
  }
}

/// The "EasyWay" wordmark that fades in and slides up during the intro.
class SplashWordmark extends StatelessWidget {
  const SplashWordmark({super.key, required this.reveal});

  final Animation<double> reveal;

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: reveal,
      builder: (context, child) {
        return Opacity(
          opacity: reveal.value.clamp(0.0, 1.0),
          child: Transform.translate(
            offset: Offset(0, 16 * (1 - reveal.value)),
            child: child,
          ),
        );
      },
      child: RichText(
        text: TextSpan(
          children: [
            TextSpan(
              text: 'Easy',
              style: ClientTypography.displayLarge(context).copyWith(
                color: ClientColors.textPrimaryFor(context),
                height: 1,
              ),
            ),
            TextSpan(
              text: 'Way',
              style: ClientTypography.displayLarge(
                context,
              ).copyWith(color: ClientColors.primaryFor(context), height: 1),
            ),
          ],
        ),
      ),
    );
  }
}
