// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYokdjb2LRrqfwXL8bkqWgiqE_z_1QpCY',
    appId: '1:109061265959:web:7312c4acbfce223587cc02',
    messagingSenderId: '109061265959',
    projectId: 'easyway-ece0c',
    authDomain: 'easyway-ece0c.firebaseapp.com',
    storageBucket: 'easyway-ece0c.firebasestorage.app',
    measurementId: 'G-GS6YFL7GNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Kz-skp3vBAdtmzNXgMAdjYabseKJ9Y8',
    appId: '1:109061265959:android:dc604d27d907660387cc02',
    messagingSenderId: '109061265959',
    projectId: 'easyway-ece0c',
    storageBucket: 'easyway-ece0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5XQGiXhGHsGk75XvZreTR-tz4OUbok3M',
    appId: '1:109061265959:ios:feaf5184cc51bfc087cc02',
    messagingSenderId: '109061265959',
    projectId: 'easyway-ece0c',
    storageBucket: 'easyway-ece0c.firebasestorage.app',
    iosBundleId: 'com.bmt.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5XQGiXhGHsGk75XvZreTR-tz4OUbok3M',
    appId: '1:109061265959:ios:a2e49f37e094228d87cc02',
    messagingSenderId: '109061265959',
    projectId: 'easyway-ece0c',
    storageBucket: 'easyway-ece0c.firebasestorage.app',
    iosBundleId: 'com.example.bmtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYokdjb2LRrqfwXL8bkqWgiqE_z_1QpCY',
    appId: '1:109061265959:web:efbe8a36a17b845087cc02',
    messagingSenderId: '109061265959',
    projectId: 'easyway-ece0c',
    authDomain: 'easyway-ece0c.firebaseapp.com',
    storageBucket: 'easyway-ece0c.firebasestorage.app',
    measurementId: 'G-L4Z074E11N',
  );
}
